[2022-12-15 15:16:27,063] | INFO | Watching for file changes with StatReloader
[2022-12-15 15:34:21,269] | INFO | Watching for file changes with StatReloader
[2022-12-15 17:29:42,730] | INFO | wheelside@mail.ru нет доступа
[2022-12-15 17:29:42,817] | WARNING | Forbidden: /users/password/
[2022-12-15 17:29:42,817] | WARNING | "GET /users/password/ HTTP/1.1" 403 25
[2022-12-15 17:29:44,104] | INFO | wheelside@mail.ru нет доступа
[2022-12-15 17:29:44,126] | WARNING | Forbidden: /users/password/
[2022-12-15 17:29:44,126] | WARNING | "GET /users/password/ HTTP/1.1" 403 25
[2022-12-15 17:29:45,349] | INFO | wheelside@mail.ru нет доступа
[2022-12-15 17:29:45,369] | WARNING | Forbidden: /users/password/
[2022-12-15 17:29:45,370] | WARNING | "GET /users/password/ HTTP/1.1" 403 25
[2022-12-15 17:49:08,823] | INFO | Watching for file changes with StatReloader
[2022-12-15 17:49:10,154] | INFO | "GET / HTTP/1.1" 200 57173
[2022-12-15 17:49:11,089] | INFO | "GET / HTTP/1.1" 200 57172
[2022-12-15 17:49:11,100] | INFO | "GET /static/admin/css/base.css HTTP/1.1" 304 0
[2022-12-15 17:49:11,112] | INFO | "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[2022-12-15 17:49:11,116] | INFO | "GET /static/admin_tools/css/menu.css HTTP/1.1" 304 0
[2022-12-15 17:49:11,116] | INFO | "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
[2022-12-15 17:49:11,117] | INFO | "GET /static/admin_tools/css/dashboard.css HTTP/1.1" 304 0
[2022-12-15 17:49:11,118] | INFO | "GET /static/admin_tools/css/jquery/jquery-ui.css HTTP/1.1" 304 0
[2022-12-15 17:49:11,120] | INFO | "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[2022-12-15 17:49:11,120] | INFO | "GET /static/admin_tools/js/utils.js HTTP/1.1" 304 0
[2022-12-15 17:49:11,147] | INFO | "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
[2022-12-15 17:49:11,164] | INFO | "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[2022-12-15 17:49:11,213] | INFO | "GET /static/admin_tools/js/jquery/jquery.min.js HTTP/1.1" 304 0
[2022-12-15 17:49:11,218] | INFO | "GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
[2022-12-15 17:49:11,220] | INFO | "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[2022-12-15 17:49:11,220] | INFO | "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[2022-12-15 17:49:11,221] | INFO | "GET /static/admin_tools/images/admin-tools.png HTTP/1.1" 304 0
[2022-12-15 17:49:11,274] | INFO | "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
[2022-12-15 17:49:11,280] | INFO | "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[2022-12-15 17:49:11,281] | INFO | "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[2022-12-15 17:49:11,281] | INFO | "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[2022-12-15 17:49:11,438] | INFO | "GET /static/admin_tools/js/jquery/jquery-ui.min.js HTTP/1.1" 304 0
[2022-12-15 17:49:11,448] | INFO | "GET /static/admin_tools/js/menu.js HTTP/1.1" 304 0
[2022-12-15 17:49:11,478] | INFO | "GET /static/admin_tools/js/jquery/jquery.cookie.min.js HTTP/1.1" 304 0
[2022-12-15 17:49:11,486] | INFO | "GET /static/admin_tools/js/jquery/jquery.dashboard.js HTTP/1.1" 304 0
[2022-12-15 17:49:11,532] | INFO | "GET /static/admin_tools/js/dashboard.js HTTP/1.1" 304 0
[2022-12-15 17:49:11,611] | INFO | "GET /static/admin_tools/css/jquery/images/ui-bg_flat_75_ffffff_40x100.png HTTP/1.1" 304 0
[2022-12-15 17:49:11,611] | INFO | "GET /static/admin_tools/css/jquery/images/ui-bg_glass_75_e6e6e6_1x400.png HTTP/1.1" 304 0
[2022-12-15 17:49:11,611] | INFO | "GET /static/admin_tools/css/jquery/images/ui-bg_glass_65_ffffff_1x400.png HTTP/1.1" 304 0
[2022-12-15 17:49:19,862] | INFO | wheelside@mail.ru нет доступа
[2022-12-15 17:49:19,896] | WARNING | Forbidden: /users/password/
[2022-12-15 17:49:19,896] | WARNING | "GET /users/password/ HTTP/1.1" 403 25
[2022-12-15 17:49:50,762] | INFO | wheelside@mail.ru нет доступа
[2022-12-15 17:49:50,785] | WARNING | Forbidden: /users/password/
[2022-12-15 17:49:50,785] | WARNING | "GET /users/password/ HTTP/1.1" 403 25
[2022-12-17 15:58:56,182] | INFO | michael@gmail.com нет доступа
[2022-12-17 15:58:56,184] | WARNING | Forbidden: /users/password/
[2022-12-17 15:58:57,132] | INFO | michael@gmail.com успешно изменил пароль
[2022-12-17 15:59:00,353] | INFO | Watching for file changes with StatReloader
[2022-12-17 15:59:28,959] | INFO | "GET / HTTP/1.1" 302 0
[2022-12-17 15:59:29,036] | INFO | "GET /login/?next=/ HTTP/1.1" 200 12929
[2022-12-17 15:59:29,050] | INFO | "GET /static/admin/css/base.css HTTP/1.1" 200 16378
[2022-12-17 15:59:29,051] | INFO | "GET /static/admin/css/login.css HTTP/1.1" 200 1233
[2022-12-17 15:59:29,059] | INFO | "GET /static/admin/css/theming_v4.css HTTP/1.1" 200 1748
[2022-12-17 15:59:29,060] | INFO | "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 11479
[2022-12-17 15:59:29,061] | INFO | "GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
[2022-12-17 15:59:29,098] | INFO | "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 11275
[2022-12-17 15:59:29,110] | INFO | "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[2022-12-17 15:59:29,111] | INFO | "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
[2022-12-17 15:59:29,141] | INFO | "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 3531
[2022-12-17 15:59:29,175] | INFO | "GET /static/admin/img/logo.png HTTP/1.1" 200 2947
[2022-12-17 15:59:29,206] | INFO | "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[2022-12-17 15:59:29,213] | INFO | "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[2022-12-17 15:59:29,232] | INFO | "GET /static/admin/img/favicon.ico HTTP/1.1" 200 8348
[2022-12-17 15:59:43,936] | INFO | "POST /login/?next=/ HTTP/1.1" 200 13169
[2022-12-17 15:59:43,949] | INFO | "GET /static/admin/css/base.css HTTP/1.1" 304 0
[2022-12-17 15:59:43,952] | INFO | "GET /static/admin/css/login.css HTTP/1.1" 304 0
[2022-12-17 15:59:43,955] | INFO | "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[2022-12-17 15:59:43,955] | INFO | "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
[2022-12-17 15:59:43,968] | INFO | "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
[2022-12-17 15:59:43,969] | INFO | "GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
[2022-12-17 15:59:44,005] | INFO | "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[2022-12-17 15:59:44,021] | INFO | "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
[2022-12-17 15:59:44,112] | INFO | "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[2022-12-17 15:59:44,112] | INFO | "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[2022-12-17 15:59:44,121] | INFO | "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[2022-12-17 16:00:35,878] | INFO | "POST /login/?next=/ HTTP/1.1" 302 0
[2022-12-17 16:00:36,352] | INFO | "GET / HTTP/1.1" 200 57172
[2022-12-17 16:00:36,365] | INFO | "GET /static/admin/css/base.css HTTP/1.1" 304 0
[2022-12-17 16:00:36,367] | INFO | "GET /static/admin_tools/css/menu.css HTTP/1.1" 200 5349
[2022-12-17 16:00:36,370] | INFO | "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[2022-12-17 16:00:36,380] | INFO | "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[2022-12-17 16:00:36,380] | INFO | "GET /static/admin_tools/js/utils.js HTTP/1.1" 200 1203
[2022-12-17 16:00:36,381] | INFO | "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
[2022-12-17 16:00:36,381] | INFO | "GET /static/admin_tools/css/jquery/jquery-ui.css HTTP/1.1" 200 31890
[2022-12-17 16:00:36,382] | INFO | "GET /static/admin_tools/css/dashboard.css HTTP/1.1" 200 6388
[2022-12-17 16:00:36,394] | INFO | "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
[2022-12-17 16:00:36,436] | INFO | "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[2022-12-17 16:00:36,485] | INFO | "GET /static/admin_tools/js/jquery/jquery.min.js HTTP/1.1" 200 89501
[2022-12-17 16:00:36,494] | INFO | "GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
[2022-12-17 16:00:36,495] | INFO | "GET /static/admin_tools/images/admin-tools.png HTTP/1.1" 200 7013
[2022-12-17 16:00:36,504] | INFO | "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[2022-12-17 16:00:36,505] | INFO | "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[2022-12-17 16:00:36,506] | INFO | "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[2022-12-17 16:00:36,508] | INFO | "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2022-12-17 16:00:36,508] | INFO | "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2022-12-17 16:00:36,528] | INFO | "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
[2022-12-17 16:00:36,560] | INFO | "GET /static/admin_tools/js/jquery/jquery-ui.min.js HTTP/1.1" 200 253668
[2022-12-17 16:00:36,566] | INFO | "GET /static/admin_tools/js/menu.js HTTP/1.1" 200 2154
[2022-12-17 16:00:36,678] | INFO | "GET /static/admin_tools/js/jquery/jquery.cookie.min.js HTTP/1.1" 200 1043
[2022-12-17 16:00:36,689] | INFO | "GET /static/admin_tools/js/jquery/jquery.dashboard.js HTTP/1.1" 200 13231
[2022-12-17 16:00:36,698] | INFO | "GET /static/admin_tools/js/dashboard.js HTTP/1.1" 200 495
[2022-12-17 16:00:36,778] | INFO | "GET /static/admin_tools/css/jquery/images/ui-bg_flat_75_ffffff_40x100.png HTTP/1.1" 200 208
[2022-12-17 16:00:36,780] | INFO | "GET /static/admin_tools/css/jquery/images/ui-bg_glass_65_ffffff_1x400.png HTTP/1.1" 200 207
[2022-12-17 16:00:36,780] | INFO | "GET /static/admin_tools/css/jquery/images/ui-bg_glass_75_e6e6e6_1x400.png HTTP/1.1" 200 262
[2022-12-17 16:01:54,303] | INFO | michael@gmail.com нет доступа
[2022-12-17 16:01:54,303] | WARNING | Forbidden: /users/password/
[2022-12-17 16:01:54,832] | INFO | michael@gmail.com успешно изменил пароль
[2022-12-17 16:02:26,490] | INFO | michael@gmail.com нет доступа
[2022-12-17 16:02:26,491] | WARNING | Forbidden: /users/password/
[2022-12-17 16:02:27,162] | INFO | michael@gmail.com успешно изменил пароль
[2022-12-17 16:03:23,406] | INFO | michael@gmail.com нет доступа
[2022-12-17 16:03:23,407] | WARNING | Forbidden: /users/password/
[2022-12-17 16:03:24,044] | INFO | michael@gmail.com успешно изменил пароль
[2022-12-17 16:05:24,915] | INFO | michael@gmail.com нет доступа
[2022-12-17 16:05:24,916] | WARNING | Forbidden: /users/password/
[2022-12-17 16:05:25,490] | INFO | michael@gmail.com успешно изменил пароль
[2022-12-17 16:15:41,083] | INFO | michael@gmail.com нет доступа
[2022-12-17 16:15:41,083] | WARNING | Forbidden: /users/password/
[2022-12-17 16:15:41,693] | INFO | michael@gmail.com успешно изменил пароль
[2022-12-17 16:18:08,966] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-17 16:18:10,324] | INFO | Watching for file changes with StatReloader
[2022-12-17 16:18:38,417] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-17 16:18:39,689] | INFO | Watching for file changes with StatReloader
[2022-12-17 16:29:14,791] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-17 16:29:16,093] | INFO | Watching for file changes with StatReloader
[2022-12-17 16:29:28,371] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-17 16:29:29,677] | INFO | Watching for file changes with StatReloader
[2022-12-17 16:29:42,094] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-17 16:29:43,355] | INFO | Watching for file changes with StatReloader
[2022-12-17 16:30:26,274] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-17 16:30:27,532] | INFO | Watching for file changes with StatReloader
[2022-12-17 16:40:48,460] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-17 16:40:49,769] | INFO | Watching for file changes with StatReloader
[2022-12-17 16:40:56,761] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-17 16:40:58,045] | INFO | Watching for file changes with StatReloader
[2022-12-19 11:39:59,842] | INFO | Watching for file changes with StatReloader
[2022-12-19 11:40:06,569] | INFO | "GET / HTTP/1.1" 200 57173
[2022-12-19 11:40:06,589] | INFO | "GET /static/admin_tools/css/menu.css HTTP/1.1" 304 0
[2022-12-19 11:40:06,589] | INFO | "GET /static/admin/css/base.css HTTP/1.1" 304 0
[2022-12-19 11:40:06,590] | INFO | "GET /static/admin_tools/css/jquery/jquery-ui.css HTTP/1.1" 200 31890
[2022-12-19 11:40:06,594] | INFO | "GET /static/admin/css/theming_v4.css HTTP/1.1" 304 0
[2022-12-19 11:40:06,595] | INFO | "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
[2022-12-19 11:40:06,597] | INFO | "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[2022-12-19 11:40:06,598] | INFO | "GET /static/admin_tools/js/utils.js HTTP/1.1" 304 0
[2022-12-19 11:40:06,601] | INFO | "GET /static/admin_tools/css/dashboard.css HTTP/1.1" 304 0
[2022-12-19 11:40:06,605] | INFO | "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[2022-12-19 11:40:06,671] | INFO | "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
[2022-12-19 11:40:06,675] | INFO | "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[2022-12-19 11:40:06,726] | INFO | "GET /static/admin_tools/js/jquery/jquery.min.js HTTP/1.1" 200 89501
[2022-12-19 11:40:06,742] | INFO | "GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
[2022-12-19 11:40:06,745] | INFO | "GET /static/admin_tools/images/admin-tools.png HTTP/1.1" 304 0
[2022-12-19 11:40:06,746] | INFO | "GET /static/admin/img/logo.png HTTP/1.1" 304 0
[2022-12-19 11:40:06,746] | INFO | "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[2022-12-19 11:40:06,747] | INFO | "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[2022-12-19 11:40:06,808] | INFO | "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
[2022-12-19 11:40:06,817] | INFO | "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[2022-12-19 11:40:06,817] | INFO | "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[2022-12-19 11:40:06,817] | INFO | "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[2022-12-19 11:40:06,993] | INFO | "GET /static/admin_tools/js/jquery/jquery-ui.min.js HTTP/1.1" 200 253668
[2022-12-19 11:40:06,998] | INFO | "GET /static/admin_tools/js/menu.js HTTP/1.1" 304 0
[2022-12-19 11:40:07,049] | INFO | "GET /static/admin_tools/js/jquery/jquery.cookie.min.js HTTP/1.1" 304 0
[2022-12-19 11:40:07,099] | INFO | "GET /static/admin_tools/js/jquery/jquery.dashboard.js HTTP/1.1" 304 0
[2022-12-19 11:40:07,145] | INFO | "GET /static/admin_tools/js/dashboard.js HTTP/1.1" 304 0
[2022-12-19 11:40:07,220] | INFO | "GET /static/admin_tools/css/jquery/images/ui-bg_glass_65_ffffff_1x400.png HTTP/1.1" 304 0
[2022-12-19 11:40:07,221] | INFO | "GET /static/admin_tools/css/jquery/images/ui-bg_flat_75_ffffff_40x100.png HTTP/1.1" 304 0
[2022-12-19 11:40:07,222] | INFO | "GET /static/admin_tools/css/jquery/images/ui-bg_glass_75_e6e6e6_1x400.png HTTP/1.1" 304 0
[2022-12-19 11:42:44,573] | INFO | Watching for file changes with StatReloader
[2022-12-19 11:43:28,350] | INFO | Watching for file changes with StatReloader
[2022-12-19 11:43:36,240] | INFO | "GET / HTTP/1.1" 200 57172
[2022-12-19 11:50:00,682] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-19 11:50:02,151] | INFO | Watching for file changes with StatReloader
[2022-12-19 11:50:04,919] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-19 11:50:06,280] | INFO | Watching for file changes with StatReloader
[2022-12-19 12:12:35,257] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-19 12:12:36,809] | INFO | Watching for file changes with StatReloader
[2022-12-19 12:24:42,593] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-19 12:24:44,137] | INFO | Watching for file changes with StatReloader
[2022-12-19 12:59:03,218] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-19 12:59:04,856] | INFO | Watching for file changes with StatReloader
[2022-12-19 13:01:22,700] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-19 13:01:24,149] | INFO | Watching for file changes with StatReloader
[2022-12-19 13:06:28,962] | INFO | Watching for file changes with StatReloader
[2022-12-19 13:09:54,394] | INFO | Watching for file changes with StatReloader
[2022-12-19 13:16:38,051] | INFO | Watching for file changes with StatReloader
[2022-12-19 13:24:51,214] | INFO | Watching for file changes with StatReloader
[2022-12-20 12:56:34,246] | INFO | Watching for file changes with StatReloader
[2022-12-20 12:56:41,252] | ERROR | Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 212, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 54, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[2022-12-20 12:56:41,331] | ERROR | Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 67, in __call__
    panel.generate_stats(request, response)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/panels/request.py", line 66, in generate_stats
    for k in sorted(request.session.keys())
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 125, in keys
    return self._session.keys()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[2022-12-20 12:56:41,333] | ERROR | "GET / HTTP/1.1" 500 153310
[2022-12-20 12:56:41,692] | ERROR | Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 67, in __call__
    panel.generate_stats(request, response)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/panels/request.py", line 66, in generate_stats
    for k in sorted(request.session.keys())
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 125, in keys
    return self._session.keys()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[2022-12-20 12:56:41,693] | ERROR | "GET /favicon.ico HTTP/1.1" 500 152374
[2022-12-20 12:57:31,302] | INFO | Watching for file changes with StatReloader
[2022-12-20 12:57:34,479] | ERROR | Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 212, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 54, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[2022-12-20 12:57:34,564] | ERROR | Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 67, in __call__
    panel.generate_stats(request, response)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/panels/request.py", line 66, in generate_stats
    for k in sorted(request.session.keys())
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 125, in keys
    return self._session.keys()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[2022-12-20 12:57:34,565] | ERROR | "GET / HTTP/1.1" 500 153312
[2022-12-20 12:57:34,839] | ERROR | Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 67, in __call__
    panel.generate_stats(request, response)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/panels/request.py", line 66, in generate_stats
    for k in sorted(request.session.keys())
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 125, in keys
    return self._session.keys()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[2022-12-20 12:57:34,840] | ERROR | "GET /favicon.ico HTTP/1.1" 500 152374
[2022-12-20 12:58:08,394] | INFO | "GET / HTTP/1.1" 302 0
[2022-12-20 12:58:08,438] | INFO | "GET /login/?next=/ HTTP/1.1" 200 12929
[2022-12-20 12:58:08,453] | INFO | "GET /static/admin/css/login.css HTTP/1.1" 200 1233
[2022-12-20 12:58:08,455] | INFO | "GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
[2022-12-20 12:58:08,463] | INFO | "GET /static/admin/css/theming_v4.css HTTP/1.1" 304 0
[2022-12-20 12:58:08,470] | INFO | "GET /static/admin/css/base.css HTTP/1.1" 200 16378
[2022-12-20 12:58:08,470] | INFO | "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 11479
[2022-12-20 12:58:08,474] | INFO | "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 11275
[2022-12-20 12:58:08,487] | INFO | "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[2022-12-20 12:58:08,488] | INFO | "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
[2022-12-20 12:58:08,538] | INFO | "GET /static/admin/img/logo.png HTTP/1.1" 304 0
[2022-12-20 12:58:08,560] | INFO | "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 3531
[2022-12-20 12:58:08,562] | INFO | "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[2022-12-20 12:58:08,566] | INFO | "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[2022-12-20 12:58:08,791] | INFO | "GET /static/admin/img/favicon.ico HTTP/1.1" 304 0
[2022-12-20 12:58:39,431] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 12:58:40,677] | INFO | Watching for file changes with StatReloader
[2022-12-20 13:04:03,421] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 13:04:04,724] | INFO | Watching for file changes with StatReloader
[2022-12-20 13:04:31,777] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 13:04:33,010] | INFO | Watching for file changes with StatReloader
[2022-12-20 13:04:43,147] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 13:04:44,551] | INFO | Watching for file changes with StatReloader
[2022-12-20 13:06:05,598] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 13:06:06,871] | INFO | Watching for file changes with StatReloader
[2022-12-20 13:36:41,058] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 13:36:42,382] | INFO | Watching for file changes with StatReloader
[2022-12-20 13:37:49,641] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 13:37:50,880] | INFO | Watching for file changes with StatReloader
[2022-12-20 13:50:36,107] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 13:50:37,440] | INFO | Watching for file changes with StatReloader
[2022-12-20 13:53:39,851] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 13:53:41,100] | INFO | Watching for file changes with StatReloader
[2022-12-20 13:55:32,646] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 13:55:33,953] | INFO | Watching for file changes with StatReloader
[2022-12-20 13:58:02,408] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 13:58:03,712] | INFO | Watching for file changes with StatReloader
[2022-12-20 14:05:19,568] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 14:05:20,854] | INFO | Watching for file changes with StatReloader
[2022-12-20 14:06:15,325] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 14:06:16,605] | INFO | Watching for file changes with StatReloader
[2022-12-20 14:07:39,610] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 14:07:40,858] | INFO | Watching for file changes with StatReloader
[2022-12-20 14:21:53,520] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 14:21:54,825] | INFO | Watching for file changes with StatReloader
[2022-12-20 14:45:04,223] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 14:45:05,607] | INFO | Watching for file changes with StatReloader
[2022-12-20 14:48:14,401] | INFO | Watching for file changes with StatReloader
[2022-12-20 14:54:21,046] | INFO | Watching for file changes with StatReloader
[2022-12-20 14:54:56,643] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-20 14:54:57,986] | INFO | Watching for file changes with StatReloader
[2022-12-21 20:36:19,776] | INFO | Watching for file changes with StatReloader
[2022-12-21 20:38:19,169] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-21 20:38:20,443] | INFO | Watching for file changes with StatReloader
[2022-12-21 20:38:26,320] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-21 20:38:27,515] | INFO | Watching for file changes with StatReloader
[2022-12-21 21:25:31,622] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-21 21:25:33,417] | INFO | Watching for file changes with StatReloader
[2022-12-21 21:28:08,654] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-21 21:28:09,940] | INFO | Watching for file changes with StatReloader
[2022-12-21 21:34:34,586] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-21 21:34:35,972] | INFO | Watching for file changes with StatReloader
[2022-12-21 21:34:46,023] | INFO | /code/src/application/users/views.py changed, reloading.
[2022-12-21 21:34:47,225] | INFO | Watching for file changes with StatReloader
